### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-manage-api-php-client#37]
1. add `X-KBC-ManageApiToken` to every example where it is needed
2. update default backend to snowflake (it's saying mysql is default) for create project api call

**Comment by ujovlado** [comment]
https://keboola.zendesk.com/agent/tickets/8221

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C0A5ZK1LY/p1523439847000094
