### ISSUE TITLE
More stable notifications tests

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-manage-api-php-client#6]
![image](https://cloud.githubusercontent.com/assets/903531/12890867/cce3aad2-ce85-11e5-8f20-4ad5e568aedd.png)

https://jenkins.keboola.com/view/Connection/job/Manage%20API%20testing/189/console

Testy notifikací náhodně failují, je to dané fixními sleep čekající na async operaci.
Tyhle typy testů bych řešil tak že to několikrát zkusí správný výsledek s nějakým backoffem. 
V sapi to stejně řeším nad eventama které jsou taky async a chvíli trvá než se založená eventa objeví v API https://github.com/keboola/storage-api-php-client/blob/94dfa6618b7802c60593ecfc0ae3205332b74412/tests/Test/StorageApiTestCase.php#L313

**Comment by MiroCillik** [comment]
Ok, tie sleepy som vyhadzal, ale zvacsim pocet pokusov v cykloch teda este.

**Comment by Halama** [comment]
jj, udělej to asi podobně jak v tom sapi testu výše

**Comment by Halama** [comment]
poslední test na to zas failnul

**Comment by Halama** [comment]
https://jenkins.keboola.com/view/Connection/job/Manage%20API%20testing/191/console
