### ISSUE TITLE
Unstable - testDeleteAndPurgeProjectWithData

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-manage-api-php-client#83]
Kolem 11 se purgují projekty vzniklé testy a zaseká to frontu. Timeout testu 120 sec potom nestačí a failne:
```
1) Keboola\ManageApiTest\ProjectDeleteTest::testDeleteAndPurgeProjectWithData
manage                         -	Exception: Project purge timeout.
```

Možné řešení:
- přidat commands queue workery na testingu (jsou tam teď dva) ať to rychleji odbaví
- zvětšit timeout v testu
- spouštět purge v noci

**Comment by yustme** [comment]
Přidal bych worker a spouštěl cron každých 15 minut. Tím se rozloží zátěž.

Je potřeba upravit deploy script a v provisioningu services.json
